- alias: turn on the kitchen light when the sun sets
  hide_entity: true
  trigger:
  - platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    service: light.turn_on
    entity_id: light.kitchen

# Pico state codes
# - On: 1
# - Up: 8
# - Fav: 2
# - Down: 16
# - Off: 4

- alias: lr pico on button pressed
  initial_state: True
  trigger:
  - platform: state
    entity_id: sensor.living_room_pico
    to: '1'
  condition:
    condition: state
    entity_id: group.living_room
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: group.living_room
    data:
      brightness_pct: 50

- alias: lr pico off button pressed
  initial_state: True
  trigger:
    - platform: state
      entity_id: sensor.living_room_pico
      to: '4'
  condition:
    condition: state
    entity_id: group.living_room
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: group.living_room

#  initial_state: True
#  trigger:
#    - platform: state
#      entity_id: sensor.living_room_pico
#      to: '8'
#  action:
#    service: homeassistant.turn_on
#    entity_id: group.living_room
#    data_template:
#      brightness: "{{ [255, state_attr('light.hue_color_lamp_1', 'brightness')|int(0) + 51]|min }}"

#- alias: lr pico dim
#  initial_state: True
#  trigger:
#    - platform: state
#      entity_id: sensor.living_room_pico
#      to: '16'
#  action:
#    service: homeassistant.turn_off
#    entity_id: group.living_room
#    data_template:
#      brightness: "{{ [0, state_attr('light.hue_color_lamp_1', 'brightness')|int(0) - 51]|max }}"
