homeassistant:
  # Name of the location where Home Assistant is running
  name: HersheyHouse
  # Location required to calculate the time the sun rises and sets
  latitude: 38.407888
  longitude: -88.349494
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 131
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

#Weather prediction:
#sensor:
#  - platform: yr

- type: weather-forecast
  entity: weather.darksky

weather:
  - platform: darksky
    api_key: 59e2826db3e375ad8d7caa52dde83fa6
    units: us

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

wemo:

light:
  - platform: tplink
    host: 192.168.1.189
    name: MBR1
  - platform: tplink
    host: 192.168.1.190
    name: MBR2
  - platform: tplink
    host: 192.168.1.191
    name: MBR3
  - platform: tplink
    host: 192.168.1.192
    name: kitchen


panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

switch:
  - platform: tplink
    host: 192.168.1.178
    name: lamp1

device_tracker:
  - platform: bluetooth_tracker

#lutron
lutron_caseta_pro:
  bridges:
    - host: 192.168.1.149
      mac: 68:9e:19:94:48:4c
